### ISSUE TITLE
Feature: Display and keep track of goal speed statistics

### ISSUE THREAD

**Issue by BrandonMcBride4** [Timmeey86/GoalPercentageCounterBakkesmodPlugin#22]
Add goal speed as a statistic to keep track of and display the most recent goal speed, minimum goal speed, maximum goal speed, and the mean/median goal speed. The average goal speed would be less memory and computation to keep track of, but the median might be more meaningful because it's not affected as much by outliers (a really fast or really slow goal).

**Comment by Timmeey86** [comment]
Based on my experience in previous features I recommend making all four a configuration option. Maybe turn median on by default

**Comment by BrandonMcBride4** [comment]
Also, this feature could keep track of max ball speed after the ball is initially hit on the most recent shot to keep track of power. This could be useful even if the ball doesn't go and measures the quality of shot.
